server {
    listen 8080;
    server_name _;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    location /health {
        access_log off;
        return 200 'SERVICE IS WORKING FOR FULLSTACK ASSESSMENT';
        default_type text/plan;
    }
}